### ISSUE TITLE
export table format

### ISSUE THREAD

**Issue by giswqs** [gee-community/ee-runner#23]
It seems the format parameter in the [export table example](https://github.com/gee-community/ee-runner/blob/master/examples/export_table.js) should be named **fileFormat** rather than **format**. I wanted to export CSV. I found that changing the example from 'GeoJSON' to 'CSV' still exports geojson. I then changed the format parameter name to **fileFormat**, and it works as expected. Here is the code:

```
var export_table = function (table, format, filename) {
  
  var json = ee.Serializer.toJSON(table);
  
  var params = {
      json: json,
      type: 'EXPORT_FEATURES',
      description: filename,
      driveFileNamePrefix: filename,
      fileFormat: format
  };
  print(filename);
  var taskId = ee.data.newTaskId(1);
  // print(taskId);
  ee.data.startProcessing(taskId, params);
};
```

**Comment by gena** [comment]
I think it depends on if you use ee.data or ee.batch. For ee.batch it is fileFormat, but for ee.data it seems to be called format.

**Comment by giswqs** [comment]
It seems the example uses ee.data. I ran the example using `ee-runner examples/export_table.js`, and the exported file is in geojson format even when I changed format to 'CSV'. However, after I changed the parameter name to **fileFormat**: 'CSV' and rerun using `ee-runner examples/export_table.js`, it did export a CSV file.

**Comment by gena** [comment]
Yeah, maybe was updated or I've simply used the wrong piece of code to create this example. I've updated the code, thanks for reporting!
