### ISSUE TITLE
running script with packages

### ISSUE THREAD

**Issue by guy1ziv2** [gee-community/ee-runner#26]
Is it possible to run a script that has a package e.g.

var g = require('users/gene/packages:geometry') ?

I tried to run on a linux by 
1. git cloning my javascript files
2. git cloning the packages into a directory called users/gene/packages

but this still reports an error. Any ideas?

**Comment by gena** [comment]
Only with some small modifications, because EE does not use standards when including packages via require(). You can put all packages in a separate folder, e.g. ./packages/, and then include as:

`var g = require('./packages/geometry')
`

**Comment by guy1ziv2** [comment]
To keep code organized - is there a way to check in the script if it runs under ee-runner or inside the Code Editor (I am cloning the scripts from googlesource.com every update). Maybe something like

if (running_on_ee_runner) {
    var g = require('./packages/geometry')
} else {
    var g = require('users/gene/packages:geometry')
}

**Comment by gena** [comment]
... hmm, you can probably try this:

```javascript
function isCommandLine() {
  try { 
    commandLine 
  }
  catch(e) {
      if(e.name == "ReferenceError") {
          return false;
      }
  }
  
  return true
}

print(isCommandLine())


```

This should return true in ee-runner and false in Code Editor

**Comment by guy1ziv2** [comment]
This is great, thanks!

Guy Ziv

**Comment by guy1ziv2** [comment]
It ended up a tiny bit more complex, because how Code Editor is looking at require(). A working script goes like this:

`if (isCommandLine()) {
  var filename = '../packages/viewshed'
  var pkg = require(filename)
} else {
  var pkg = require('users/guy1ziv2/packages:viewshed')
}
`
