### ISSUE TITLE
ee-runner terminates silently with outstanding async calls

### ISSUE THREAD

**Issue by donmccurdy** [gee-community/ee-runner#34]
Given a script that makes asynchronous requests...

```js
var image = ee.Image(1);

console.log('evaluating...');
image.evaluate((info) => {
	console.log('evaluated: ', info);
});
```

... ee-runner prints `evaluating...` and then silently exits without resolving the open requests. Since synchronous requests are not well supported outside the Code Editor (see https://github.com/google/earthengine-api/issues/151, and https://github.com/driverdan/node-XMLHttpRequest/issues/176) I've been encouraging users to write async requests instead, but then seeing this error.

**Comment by gena** [comment]
Fixed, make sure the latest version is used:

`npm install --save ee-runner@0.0.36`
